package com.xrem.example;

import java.util.List;

import com.xrem.core.DefaultOfyService;

public class GreetingDAO {
	// note - the autogenerated id is attached to the original object
	public void insertGreeting(GreetingModel greeting){
		DefaultOfyService.ofy().save().entity(greeting).now();
	}
	
	public List<GreetingModel> getGreetings(){
		return DefaultOfyService.ofy().load().type(GreetingModel.class).list();
	}
}
