package com.xrem.example;
import static com.googlecode.objectify.ObjectifyService.ofy;

import java.util.List;

public class GreetingDAO {
	// note - the autogenerated id is attached to the original object
	public void insertGreeting(GreetingModel greeting){
		ofy().save().entity(greeting).now();
	}
	
	public List<GreetingModel> getGreetings(){
		return ofy().load().type(GreetingModel.class).list();
	}
}
